name: filepicker_windows
description: A package that allows file and directory selection for Windows
  using common dialog controls.
version: 2.1.4
repository: https://github.com/halildurmus/filepicker_windows
issue_tracker: https://github.com/halildurmus/filepicker_windows/issues

topics:
  - picker
  - win32
  - ffi
  - windows

environment:
  sdk: ^3.4.0

platforms:
  windows:

dependencies:
  ffi: ^2.1.2
  win32: ^5.5.1

dev_dependencies:
  lints: ">=4.0.0 <6.0.0"
  test: ^1.25.8
