name: filepicker_windows_example
description: Demonstrates how to use the filepicker_windows package.
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  ffi: ^2.1.3
  filepicker_windows:
    path: ../../
  flutter:
    sdk: flutter
  path_provider_windows: ^2.3.0
  win32: ^5.8.0

dev_dependencies:
  lints:
    git:
      url: https://github.com/halildurmus/workflows.git
      path: packages/lints

flutter:
  uses-material-design: true
