name: filepicker_windows_example
description: Demonstrates how to use the filepicker_windows package.
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  ffi: ^2.1.2
  filepicker_windows:
    path: ../../
  flutter:
    sdk: flutter
  path_provider_windows: ^2.2.1
  win32: ^5.5.1

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
