name: Dart Examples

on:
  pull_request:
    paths:
      - .github/workflows/dart_examples.yml
      - example/*.dart
      - lib/**
      - analysis_options.yaml
      - pubspec.yaml
  push:
    branches: [main]
    paths:
      - .github/workflows/dart_examples.yml
      - example/*.dart
      - lib/**
      - analysis_options.yaml
      - pubspec.yaml

jobs:
  build:
    uses: halildurmus/workflows/.github/workflows/dart.yml@main
    with:
      analyze_directories: $(find . -type f -not \( -path .*wallpaper/* -prune \) -name '*.dart' -print)
      format_directories: $(find . -type f -not \( -path .*wallpaper/* -prune \) -name '*.dart' -print)
      run_tests: false
      working_directory: example
