name: Flutter Examples

on:
  pull_request:
    paths:
      - .github/workflows/flutter_examples.yml
      - example/wallpaper/lib/**
      - example/wallpaper/analysis_options.yaml
      - example/wallpaper/pubspec.yaml
      - lib/**
      - analysis_options.yaml
      - pubspec.yaml
  push:
    branches: [main]
    paths:
      - .github/workflows/flutter_examples.yml
      - example/wallpaper/lib/**
      - example/wallpaper/analysis_options.yaml
      - example/wallpaper/pubspec.yaml
      - lib/**
      - analysis_options.yaml
      - pubspec.yaml

jobs:
  build:
    uses: halildurmus/workflows/.github/workflows/flutter.yml@main
    with:
      analyze_directories: lib
      format_directories: lib
      run_tests: false
      working_directory: example/wallpaper
